"""add rider_locations

Revision ID: 81e80fdc6e87
Revises: 81e3a3938148
Create Date: 2026-03-13 13:03:47.280449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e80fdc6e87'
down_revision = '81e3a3938148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rider_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], name=op.f('fk_rider_locations_rider_id_riders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rider_locations'))
    )
    with op.batch_alter_table('rider_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rider_locations_rider_id'), ['rider_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rider_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rider_locations_rider_id'))

    op.drop_table('rider_locations')
    # ### end Alembic commands ###
